export const data = {
  data: {
    best_day: {
      created_at: "2021-11-16T20:18:03Z",
      date: "2021-11-15",
      id: "780cacda-60aa-4d1a-8278-f935deb4c172",
      modified_at: "2021-11-19T19:10:16Z",
      text: "8 hrs 7 mins",
      total_seconds: 29249.019002,
    },
    categories: [
      {
        decimal: "33.98",
        digital: "33:59",
        hours: 33,
        minutes: 59,
        name: "Coding",
        percent: 68.05,
        text: "33 hrs 59 mins",
        total_seconds: 122397.677894,
      },
      {
        decimal: "14.87",
        digital: "14:52",
        hours: 14,
        minutes: 52,
        name: "Browsing",
        percent: 29.77,
        text: "14 hrs 52 mins",
        total_seconds: 53542.398501,
      },
      {
        decimal: "1.08",
        digital: "1:05",
        hours: 1,
        minutes: 5,
        name: "Debugging",
        percent: 2.19,
        text: "1 hr 5 mins",
        total_seconds: 3935.011811,
      },
    ],
    created_at: "2021-11-16T20:17:51Z",
    daily_average: 17457,
    daily_average_including_other_language: 25696,
    days_including_holidays: 7,
    days_minus_holidays: 7,
    dependencies: [
      {
        decimal: "2.42",
        digital: "2:25",
        hours: 2,
        minutes: 25,
        name: "index",
        percent: 4.82,
        text: "2 hrs 25 mins",
        total_seconds: 8704.057671,
      },
      {
        decimal: "2.13",
        digital: "2:08",
        hours: 2,
        minutes: 8,
        name: "model",
        percent: 4.26,
        text: "2 hrs 8 mins",
        total_seconds: 7695.386069,
      },
      {
        decimal: "2.10",
        digital: "2:06",
        hours: 2,
        minutes: 6,
        name: "vue-router",
        percent: 4.21,
        text: "2 hrs 6 mins",
        total_seconds: 7601.364136,
      },
      {
        decimal: "1.90",
        digital: "1:54",
        hours: 1,
        minutes: 54,
        name: "store",
        percent: 3.79,
        text: "1 hr 54 mins",
        total_seconds: 6840.618163,
      },
      {
        decimal: "1.77",
        digital: "1:46",
        hours: 1,
        minutes: 46,
        name: "pinia",
        percent: 3.54,
        text: "1 hr 46 mins",
        total_seconds: 6392.221896,
      },
      {
        decimal: "1.77",
        digital: "1:46",
        hours: 1,
        minutes: 46,
        name: "404",
        percent: 3.54,
        text: "1 hr 46 mins",
        total_seconds: 6387.909242,
      },
      {
        decimal: "1.77",
        digital: "1:46",
        hours: 1,
        minutes: 46,
        name: "BasicLayout",
        percent: 3.54,
        text: "1 hr 46 mins",
        total_seconds: 6387.909242,
      },
      {
        decimal: "1.77",
        digital: "1:46",
        hours: 1,
        minutes: 46,
        name: "BlankLayout",
        percent: 3.54,
        text: "1 hr 46 mins",
        total_seconds: 6387.909242,
      },
      {
        decimal: "1.58",
        digital: "1:35",
        hours: 1,
        minutes: 35,
        name: "vue",
        percent: 3.19,
        text: "1 hr 35 mins",
        total_seconds: 5758.91993,
      },
      {
        decimal: "1.55",
        digital: "1:33",
        hours: 1,
        minutes: 33,
        name: "user",
        percent: 3.11,
        text: "1 hr 33 mins",
        total_seconds: 5612.863489,
      },
      {
        decimal: "1.08",
        digital: "1:05",
        hours: 1,
        minutes: 5,
        name: "constant",
        percent: 2.17,
        text: "1 hr 5 mins",
        total_seconds: 3920.140212,
      },
      {
        decimal: "1.02",
        digital: "1:01",
        hours: 1,
        minutes: 1,
        name: "auth",
        percent: 2.03,
        text: "1 hr 1 min",
        total_seconds: 3670.707932,
      },
      {
        decimal: "0.93",
        digital: "0:56",
        hours: 0,
        minutes: 56,
        name: "crypto",
        percent: 1.88,
        text: "56 mins",
        total_seconds: 3397.018409,
      },
      {
        decimal: "0.87",
        digital: "0:52",
        hours: 0,
        minutes: 52,
        name: "axios",
        percent: 1.75,
        text: "52 mins",
        total_seconds: 3155.424901,
      },
      {
        decimal: "0.87",
        digital: "0:52",
        hours: 0,
        minutes: 52,
        name: "ant-design-vue",
        percent: 1.73,
        text: "52 mins",
        total_seconds: 3121.293691,
      },
      {
        decimal: "0.78",
        digital: "0:47",
        hours: 0,
        minutes: 47,
        name: "core",
        percent: 1.57,
        text: "47 mins",
        total_seconds: 2837.643936,
      },
      {
        decimal: "0.73",
        digital: "0:44",
        hours: 0,
        minutes: 44,
        name: "vite",
        percent: 1.47,
        text: "44 mins",
        total_seconds: 2650.972212,
      },
      {
        decimal: "0.72",
        digital: "0:43",
        hours: 0,
        minutes: 43,
        name: "utils",
        percent: 1.44,
        text: "43 mins",
        total_seconds: 2605.370223,
      },
      {
        decimal: "0.68",
        digital: "0:41",
        hours: 0,
        minutes: 41,
        name: "http",
        percent: 1.39,
        text: "41 mins",
        total_seconds: 2511.905242,
      },
      {
        decimal: "0.67",
        digital: "0:40",
        hours: 0,
        minutes: 40,
        name: "react",
        percent: 1.36,
        text: "40 mins",
        total_seconds: 2448.84935,
      },
      {
        decimal: "0.65",
        digital: "0:39",
        hours: 0,
        minutes: 39,
        name: "router",
        percent: 1.31,
        text: "39 mins",
        total_seconds: 2361.217031,
      },
      {
        decimal: "0.63",
        digital: "0:38",
        hours: 0,
        minutes: 38,
        name: "style",
        percent: 1.29,
        text: "38 mins",
        total_seconds: 2322.68154,
      },
      {
        decimal: "0.60",
        digital: "0:36",
        hours: 0,
        minutes: 36,
        name: "message",
        percent: 1.23,
        text: "36 mins",
        total_seconds: 2218.444225,
      },
      {
        decimal: "0.60",
        digital: "0:36",
        hours: 0,
        minutes: 36,
        name: "pro-layout",
        percent: 1.21,
        text: "36 mins",
        total_seconds: 2193.041622,
      },
      {
        decimal: "0.58",
        digital: "0:35",
        hours: 0,
        minutes: 35,
        name: "sanitize",
        percent: 1.17,
        text: "35 mins",
        total_seconds: 2107.82131,
      },
      {
        decimal: "0.58",
        digital: "0:35",
        hours: 0,
        minutes: 35,
        name: "App",
        percent: 1.17,
        text: "35 mins",
        total_seconds: 2107.82131,
      },
      {
        decimal: "0.55",
        digital: "0:33",
        hours: 0,
        minutes: 33,
        name: "global",
        percent: 1.11,
        text: "33 mins",
        total_seconds: 2005.310134,
      },
      {
        decimal: "0.53",
        digital: "0:32",
        hours: 0,
        minutes: 32,
        name: "UserLayout",
        percent: 1.09,
        text: "32 mins",
        total_seconds: 1964.775966,
      },
      {
        decimal: "0.42",
        digital: "0:25",
        hours: 0,
        minutes: 25,
        name: "echarts",
        percent: 0.86,
        text: "25 mins",
        total_seconds: 1557.806003,
      },
      {
        decimal: "0.42",
        digital: "0:25",
        hours: 0,
        minutes: 25,
        name: "useTimeout",
        percent: 0.86,
        text: "25 mins",
        total_seconds: 1557.806003,
      },
      {
        decimal: "0.42",
        digital: "0:25",
        hours: 0,
        minutes: 25,
        name: "useEventListener",
        percent: 0.86,
        text: "25 mins",
        total_seconds: 1557.806003,
      },
      {
        decimal: "0.42",
        digital: "0:25",
        hours: 0,
        minutes: 25,
        name: "mockjs",
        percent: 0.86,
        text: "25 mins",
        total_seconds: 1544.440392,
      },
      {
        decimal: "0.37",
        digital: "0:22",
        hours: 0,
        minutes: 22,
        name: "common",
        percent: 0.76,
        text: "22 mins",
        total_seconds: 1379.96268,
      },
      {
        decimal: "0.35",
        digital: "0:21",
        hours: 0,
        minutes: 21,
        name: "styles",
        percent: 0.72,
        text: "21 mins",
        total_seconds: 1304.934424,
      },
      {
        decimal: "0.35",
        digital: "0:21",
        hours: 0,
        minutes: 21,
        name: "dq-antd",
        percent: 0.7,
        text: "21 mins",
        total_seconds: 1260.666528,
      },
      {
        decimal: "0.33",
        digital: "0:20",
        hours: 0,
        minutes: 20,
        name: "umi",
        percent: 0.68,
        text: "20 mins",
        total_seconds: 1221.610046,
      },
      {
        decimal: "0.30",
        digital: "0:18",
        hours: 0,
        minutes: 18,
        name: "npm",
        percent: 0.63,
        text: "18 mins",
        total_seconds: 1139.407167,
      },
      {
        decimal: "0.30",
        digital: "0:18",
        hours: 0,
        minutes: 18,
        name: "typescript",
        percent: 0.62,
        text: "18 mins",
        total_seconds: 1123.345745,
      },
      {
        decimal: "0.30",
        digital: "0:18",
        hours: 0,
        minutes: 18,
        name: "lint-staged",
        percent: 0.61,
        text: "18 mins",
        total_seconds: 1110.36746,
      },
      {
        decimal: "0.30",
        digital: "0:18",
        hours: 0,
        minutes: 18,
        name: "prettier",
        percent: 0.61,
        text: "18 mins",
        total_seconds: 1110.36746,
      },
      {
        decimal: "0.30",
        digital: "0:18",
        hours: 0,
        minutes: 18,
        name: "eslint",
        percent: 0.61,
        text: "18 mins",
        total_seconds: 1110.36746,
      },
      {
        decimal: "0.23",
        digital: "0:14",
        hours: 0,
        minutes: 14,
        name: "path",
        percent: 0.48,
        text: "14 mins",
        total_seconds: 858.531761,
      },
      {
        decimal: "0.23",
        digital: "0:14",
        hours: 0,
        minutes: 14,
        name: "plugin",
        percent: 0.48,
        text: "14 mins",
        total_seconds: 858.531761,
      },
      {
        decimal: "0.23",
        digital: "0:14",
        hours: 0,
        minutes: 14,
        name: "proxy",
        percent: 0.48,
        text: "14 mins",
        total_seconds: 858.531761,
      },
      {
        decimal: "0.23",
        digital: "0:14",
        hours: 0,
        minutes: 14,
        name: "themeConfig",
        percent: 0.48,
        text: "14 mins",
        total_seconds: 858.531761,
      },
      {
        decimal: "0.22",
        digital: "0:13",
        hours: 0,
        minutes: 13,
        name: "eslint-config-prettier",
        percent: 0.46,
        text: "13 mins",
        total_seconds: 831.177612,
      },
      {
        decimal: "0.22",
        digital: "0:13",
        hours: 0,
        minutes: 13,
        name: "commitizen",
        percent: 0.46,
        text: "13 mins",
        total_seconds: 831.177612,
      },
      {
        decimal: "0.22",
        digital: "0:13",
        hours: 0,
        minutes: 13,
        name: "husky",
        percent: 0.46,
        text: "13 mins",
        total_seconds: 831.177612,
      },
      {
        decimal: "0.22",
        digital: "0:13",
        hours: 0,
        minutes: 13,
        name: "autoprefixer",
        percent: 0.46,
        text: "13 mins",
        total_seconds: 831.177612,
      },
      {
        decimal: "0.22",
        digital: "0:13",
        hours: 0,
        minutes: 13,
        name: "eslint-plugin-prettier",
        percent: 0.46,
        text: "13 mins",
        total_seconds: 831.177612,
      },
      {
        decimal: "0.22",
        digital: "0:13",
        hours: 0,
        minutes: 13,
        name: "postcss",
        percent: 0.46,
        text: "13 mins",
        total_seconds: 831.177612,
      },
      {
        decimal: "0.22",
        digital: "0:13",
        hours: 0,
        minutes: 13,
        name: "@typescript-eslint/parser",
        percent: 0.46,
        text: "13 mins",
        total_seconds: 831.177612,
      },
      {
        decimal: "0.22",
        digital: "0:13",
        hours: 0,
        minutes: 13,
        name: "@typescript-eslint/eslint-plugin",
        percent: 0.46,
        text: "13 mins",
        total_seconds: 831.177612,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "is",
        percent: 0.42,
        text: "12 mins",
        total_seconds: 751.973038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "vite-plugin-mock",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 745.858508,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "@vitejs/plugin-vue",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "unplugin-vue-components",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "unplugin-auto-import",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "eslint-define-config",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "vue-request",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "eslint-plugin-vue",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "conventional-changelog-cli",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "postcss-less",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "jest",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "vite-plugin-style-import",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "less",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "eslint-plugin-jest",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "@vitejs/plugin-vue-jsx",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "@vueuse/head",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "@ant-design-vue/pro-layout",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "@ant-design/icons-vue",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "vue-tsc",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "postcss-html",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "vite-plugin-svg-icons",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "rimraf",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "vue-eslint-parser",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "@vitejs/plugin-legacy",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "@vueuse/core",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.20",
        digital: "0:12",
        hours: 0,
        minutes: 12,
        name: "sanitize.css",
        percent: 0.41,
        text: "12 mins",
        total_seconds: 739.457038,
      },
      {
        decimal: "0.18",
        digital: "0:11",
        hours: 0,
        minutes: 11,
        name: "classnames",
        percent: 0.37,
        text: "11 mins",
        total_seconds: 673.585983,
      },
      {
        decimal: "0.17",
        digital: "0:10",
        hours: 0,
        minutes: 10,
        name: "crypto-js",
        percent: 0.35,
        text: "10 mins",
        total_seconds: 631.495567,
      },
      {
        decimal: "0.13",
        digital: "0:08",
        hours: 0,
        minutes: 8,
        name: "notification",
        percent: 0.29,
        text: "8 mins",
        total_seconds: 515.216528,
      },
      {
        decimal: "0.13",
        digital: "0:08",
        hours: 0,
        minutes: 8,
        name: "Modal",
        percent: 0.29,
        text: "8 mins",
        total_seconds: 515.216528,
      },
      {
        decimal: "0.13",
        digital: "0:08",
        hours: 0,
        minutes: 8,
        name: "icons-vue",
        percent: 0.29,
        text: "8 mins",
        total_seconds: 515.216528,
      },
      {
        decimal: "0.12",
        digital: "0:07",
        hours: 0,
        minutes: 7,
        name: "components",
        percent: 0.26,
        text: "7 mins",
        total_seconds: 460.730827,
      },
      {
        decimal: "0.12",
        digital: "0:07",
        hours: 0,
        minutes: 7,
        name: "features",
        percent: 0.26,
        text: "7 mins",
        total_seconds: 460.730827,
      },
      {
        decimal: "0.12",
        digital: "0:07",
        hours: 0,
        minutes: 7,
        name: "renderers",
        percent: 0.26,
        text: "7 mins",
        total_seconds: 460.730827,
      },
      {
        decimal: "0.12",
        digital: "0:07",
        hours: 0,
        minutes: 7,
        name: "charts",
        percent: 0.26,
        text: "7 mins",
        total_seconds: 460.730827,
      },
      {
        decimal: "0.10",
        digital: "0:06",
        hours: 0,
        minutes: 6,
        name: "FlexBox",
        percent: 0.22,
        text: "6 mins",
        total_seconds: 403.161831,
      },
      {
        decimal: "0.10",
        digital: "0:06",
        hours: 0,
        minutes: 6,
        name: "dayjs",
        percent: 0.21,
        text: "6 mins",
        total_seconds: 387.011078,
      },
      {
        decimal: "0.10",
        digital: "0:06",
        hours: 0,
        minutes: 6,
        name: "@types/react",
        percent: 0.21,
        text: "6 mins",
        total_seconds: 370.910422,
      },
      {
        decimal: "0.10",
        digital: "0:06",
        hours: 0,
        minutes: 6,
        name: "react-dom",
        percent: 0.21,
        text: "6 mins",
        total_seconds: 370.910422,
      },
      {
        decimal: "0.10",
        digital: "0:06",
        hours: 0,
        minutes: 6,
        name: "@types/react-dom",
        percent: 0.21,
        text: "6 mins",
        total_seconds: 370.910422,
      },
      {
        decimal: "0.10",
        digital: "0:06",
        hours: 0,
        minutes: 6,
        name: "loginConfig_bg",
        percent: 0.2,
        text: "6 mins",
        total_seconds: 366.574483,
      },
      {
        decimal: "0.08",
        digital: "0:05",
        hours: 0,
        minutes: 5,
        name: "react-chrono",
        percent: 0.18,
        text: "5 mins",
        total_seconds: 329.990818,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "cross-env",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@types/express",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@umijs/route-utils",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@types/classnames",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "umi-request",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@dq-antd/pro-layout",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@types/history",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@umijs/plugin-esbuild",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "stylelint",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "dq-form",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@types/lodash.isequal",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "lodash.isequal",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "use-merge-value",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "react-helmet-async",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@umijs/plugin-blocks",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@material-ui/styles",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@types/react-helmet",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@ant-design/icons",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@umijs/preset-ant-design-pro",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "chalk",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "express",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@umijs/yorkie",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@umijs/preset-react",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "@umijs/fabric",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 279.189848,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "moment",
        percent: 0.15,
        text: "4 mins",
        total_seconds: 274.227655,
      },
      {
        decimal: "0.07",
        digital: "0:04",
        hours: 0,
        minutes: 4,
        name: "css",
        percent: 0.14,
        text: "4 mins",
        total_seconds: 255.758426,
      },
      {
        decimal: "0.05",
        digital: "0:03",
        hours: 0,
        minutes: 3,
        name: "FormCard",
        percent: 0.13,
        text: "3 mins",
        total_seconds: 230.298754,
      },
      {
        decimal: "0.05",
        digital: "0:03",
        hours: 0,
        minutes: 3,
        name: "resolvers",
        percent: 0.13,
        text: "3 mins",
        total_seconds: 227.78937,
      },
      {
        decimal: "0.05",
        digital: "0:03",
        hours: 0,
        minutes: 3,
        name: "connect",
        percent: 0.12,
        text: "3 mins",
        total_seconds: 221.533058,
      },
      {
        decimal: "0.05",
        digital: "0:03",
        hours: 0,
        minutes: 3,
        name: "Sider",
        percent: 0.12,
        text: "3 mins",
        total_seconds: 216.958883,
      },
      {
        decimal: "0.05",
        digital: "0:03",
        hours: 0,
        minutes: 3,
        name: "useMessage",
        percent: 0.11,
        text: "3 mins",
        total_seconds: 207.347173,
      },
      {
        decimal: "0.05",
        digital: "0:03",
        hours: 0,
        minutes: 3,
        name: "querystring",
        percent: 0.11,
        text: "3 mins",
        total_seconds: 203.869687,
      },
      {
        decimal: "0.05",
        digital: "0:03",
        hours: 0,
        minutes: 3,
        name: "Bg",
        percent: 0.11,
        text: "3 mins",
        total_seconds: 193.711406,
      },
      {
        decimal: "0.05",
        digital: "0:03",
        hours: 0,
        minutes: 3,
        name: "Content",
        percent: 0.11,
        text: "3 mins",
        total_seconds: 193.711406,
      },
      {
        decimal: "0.03",
        digital: "0:02",
        hours: 0,
        minutes: 2,
        name: "es",
        percent: 0.08,
        text: "2 mins",
        total_seconds: 138.697313,
      },
      {
        decimal: "0.03",
        digital: "0:02",
        hours: 0,
        minutes: 2,
        name: "dateUtil",
        percent: 0.07,
        text: "2 mins",
        total_seconds: 129.125035,
      },
      {
        decimal: "0.03",
        digital: "0:02",
        hours: 0,
        minutes: 2,
        name: "next",
        percent: 0.07,
        text: "2 mins",
        total_seconds: 128.247285,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "react-markdown",
        percent: 0.05,
        text: "1 min",
        total_seconds: 95.360592,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "eslint-plugin-jsx-a11y",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "@types/dom-to-image",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "eslint-config-next",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "@commitlint/cli",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "@commitlint/config-conventional",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "cz-conventional-changelog",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "eslint-config-airbnb",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "eslint-plugin-react-hooks",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "eslint-plugin-react",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "ts-node",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "tailwindcss",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "@types/node",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "eslint-plugin-import",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "eslint-import-resolver-typescript",
        percent: 0.05,
        text: "1 min",
        total_seconds: 91.720574,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "TimelineItemModel",
        percent: 0.05,
        text: "1 min",
        total_seconds: 82.035238,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "Post",
        percent: 0.04,
        text: "1 min",
        total_seconds: 76.907692,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "Layout",
        percent: 0.04,
        text: "1 min",
        total_seconds: 76.907692,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "antd",
        percent: 0.04,
        text: "1 min",
        total_seconds: 64.851372,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "router.config",
        percent: 0.03,
        text: "0 secs",
        total_seconds: 50.18058,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "Theme",
        percent: 0.03,
        text: "0 secs",
        total_seconds: 48.253876,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "defaultVariable",
        percent: 0.02,
        text: "0 secs",
        total_seconds: 44.056515,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "LinkButton",
        percent: 0.02,
        text: "0 secs",
        total_seconds: 29.13184,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "form",
        percent: 0.02,
        text: "0 secs",
        total_seconds: 27.821652,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "typings",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 26.583271,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "vue-types",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 26.583271,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "Header",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 23.247477,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "@emotion/react",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 18.310767,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "@prisma/client",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 18.310767,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "@chakra-ui/react",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 18.310767,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "@emotion/styled",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 18.310767,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "framer-motion",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 18.310767,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "ffprobe",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 16.061422,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "fs-extra",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 16.061422,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "pify",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 16.061422,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "ffprobe-static",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 16.061422,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "exif",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 16.061422,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "prisma",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 15.259155,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "*",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 14.639232,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "createProdMockServer",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 14.639232,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "tslint",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 12.978285,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "reset",
        percent: 0.01,
        text: "0 secs",
        total_seconds: 9.347194,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "theme",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 8.584483,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "MyIcon",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "ChooseFileModal",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "API",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "PageSider",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "FileDir",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "interface",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "UploadingModal",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "Tree",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "storage",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "FileTable",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "SiderTree",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "UploadErrorModal",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "PageContent",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "file",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.277078,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "TimelineModel",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 4.328379,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "focus-visible",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 4.328379,
      },
    ],
    editors: [
      {
        decimal: "33.98",
        digital: "33:59",
        hours: 33,
        minutes: 59,
        name: "VS Code",
        percent: 68.05,
        text: "33 hrs 59 mins",
        total_seconds: 122397.677894,
      },
      {
        decimal: "15.95",
        digital: "15:57",
        hours: 15,
        minutes: 57,
        name: "Browser",
        percent: 31.95,
        text: "15 hrs 57 mins",
        total_seconds: 57477.410312,
      },
    ],
    end: "2021-11-19T15:59:59Z",
    holidays: 0,
    human_readable_daily_average: "4 hrs 50 mins",
    human_readable_daily_average_including_other_language: "7 hrs 8 mins",
    human_readable_range: "last week",
    human_readable_total: "33 hrs 56 mins",
    human_readable_total_including_other_language: "49 hrs 57 mins",
    id: "db6e9cdf-3c5a-45c9-8efe-f6dc1103d093",
    is_already_updating: false,
    is_coding_activity_visible: true,
    is_including_today: false,
    is_other_usage_visible: true,
    is_stuck: false,
    is_up_to_date: true,
    languages: [
      {
        decimal: "19.87",
        digital: "19:52",
        hours: 19,
        minutes: 52,
        name: "Vue.js",
        percent: 39.79,
        text: "19 hrs 52 mins",
        total_seconds: 71568.88904,
      },
      {
        decimal: "16.02",
        digital: "16:01",
        hours: 16,
        minutes: 1,
        name: "Other",
        percent: 32.06,
        text: "16 hrs 1 min",
        total_seconds: 57675.478755,
      },
      {
        decimal: "9.52",
        digital: "9:31",
        hours: 9,
        minutes: 31,
        name: "TypeScript",
        percent: 19.07,
        text: "9 hrs 31 mins",
        total_seconds: 34299.402241,
      },
      {
        decimal: "2.03",
        digital: "2:02",
        hours: 2,
        minutes: 2,
        name: "JavaScript",
        percent: 4.09,
        text: "2 hrs 2 mins",
        total_seconds: 7361.922581,
      },
      {
        decimal: "1.97",
        digital: "1:58",
        hours: 1,
        minutes: 58,
        name: "Markdown",
        percent: 3.94,
        text: "1 hr 58 mins",
        total_seconds: 7088.307231,
      },
      {
        decimal: "0.35",
        digital: "0:21",
        hours: 0,
        minutes: 21,
        name: "JSON",
        percent: 0.71,
        text: "21 mins",
        total_seconds: 1269.274594,
      },
      {
        decimal: "0.08",
        digital: "0:05",
        hours: 0,
        minutes: 5,
        name: "LESS",
        percent: 0.19,
        text: "5 mins",
        total_seconds: 349.345843,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "Git Config",
        percent: 0.06,
        text: "1 min",
        total_seconds: 105.219485,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "Docker",
        percent: 0.03,
        text: "0 secs",
        total_seconds: 55.496585,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "YAML",
        percent: 0.03,
        text: "0 secs",
        total_seconds: 48.770724,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "Bash",
        percent: 0.03,
        text: "0 secs",
        total_seconds: 48.645003,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "CSS",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 4.336124,
      },
    ],
    machines: [
      {
        decimal: "30.63",
        digital: "30:38",
        hours: 30,
        machine: {
          created_at: "2021-08-19T03:57:59Z",
          id: "466bdc4b-7148-4c62-9774-c74408afdb73",
          ip: "183.129.146.132",
          last_seen_at: "2021-11-19T11:13:02Z",
          name: "LAPTOP-GA8DQVHK",
          value: "LAPTOP-GA8DQVHK",
        },
        minutes: 38,
        name: "LAPTOP-GA8DQVHK",
        percent: 61.33,
        text: "30 hrs 38 mins",
        total_seconds: 110312.731763,
      },
      {
        decimal: "15.95",
        digital: "15:57",
        hours: 15,
        machine: {
          created_at: "2021-10-26T12:45:15Z",
          id: "929d9f3a-1774-4b2e-af1c-a920f7212afd",
          ip: "218.253.154.190",
          last_seen_at: "2021-11-20T03:36:27Z",
          name: "Unknown Hostname",
          value: "Unknown Hostname",
        },
        minutes: 57,
        name: "Unknown Hostname",
        percent: 31.95,
        text: "15 hrs 57 mins",
        total_seconds: 57477.410312,
      },
      {
        decimal: "3.35",
        digital: "3:21",
        hours: 3,
        machine: {
          created_at: "2021-10-27T13:26:38Z",
          id: "7aa7b08b-f829-42b9-a73b-8562fc94a404",
          ip: "112.10.218.1",
          last_seen_at: "2021-11-15T14:26:09Z",
          name: "sunss",
          value: "sunss",
        },
        minutes: 21,
        name: "sunss",
        percent: 6.72,
        text: "3 hrs 21 mins",
        total_seconds: 12084.946131,
      },
    ],
    modified_at: "2021-11-19T19:10:16Z",
    operating_systems: [
      {
        decimal: "49.95",
        digital: "49:57",
        hours: 49,
        minutes: 57,
        name: "Windows",
        percent: 100.0,
        text: "49 hrs 57 mins",
        total_seconds: 179875.088206,
      },
    ],
    percent_calculated: 100,
    project: null,
    projects: [
      {
        decimal: "33.40",
        digital: "33:24",
        hours: 33,
        minutes: 24,
        name: "simpleChain-vue-m-pc",
        percent: 66.88,
        text: "33 hrs 24 mins",
        total_seconds: 120294.133749,
      },
      {
        decimal: "14.12",
        digital: "14:07",
        hours: 14,
        minutes: 7,
        name: "photo",
        percent: 28.26,
        text: "14 hrs 7 mins",
        total_seconds: 50837.667529,
      },
      {
        decimal: "0.97",
        digital: "0:58",
        hours: 0,
        minutes: 58,
        name: "vuepress",
        percent: 1.96,
        text: "58 mins",
        total_seconds: 3517.562333,
      },
      {
        decimal: "0.73",
        digital: "0:44",
        hours: 0,
        minutes: 44,
        name: "frontend-lowcode-application",
        percent: 1.49,
        text: "44 mins",
        total_seconds: 2671.76739,
      },
      {
        decimal: "0.23",
        digital: "0:14",
        hours: 0,
        minutes: 14,
        name: "I-You",
        percent: 0.49,
        text: "14 mins",
        total_seconds: 889.947812,
      },
      {
        decimal: "0.13",
        digital: "0:08",
        hours: 0,
        minutes: 8,
        name: "node-ts-app",
        percent: 0.29,
        text: "8 mins",
        total_seconds: 527.576631,
      },
      {
        decimal: "0.13",
        digital: "0:08",
        hours: 0,
        minutes: 8,
        name: "nbfi-management-frontend",
        percent: 0.29,
        text: "8 mins",
        total_seconds: 522.470974,
      },
      {
        decimal: "0.10",
        digital: "0:06",
        hours: 0,
        minutes: 6,
        name: "frontend-emrrs",
        percent: 0.23,
        text: "6 mins",
        total_seconds: 419.969771,
      },
      {
        decimal: "0.02",
        digital: "0:01",
        hours: 0,
        minutes: 1,
        name: "test-demo",
        percent: 0.04,
        text: "1 min",
        total_seconds: 80.760839,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "frontend-lowcode-management",
        percent: 0.03,
        text: "0 secs",
        total_seconds: 54.222393,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "frontend-mrds",
        percent: 0.03,
        text: "0 secs",
        total_seconds: 51.09821,
      },
      {
        decimal: "0.00",
        digital: "0:00",
        hours: 0,
        minutes: 0,
        name: "native-javascript-learn",
        percent: 0.0,
        text: "0 secs",
        total_seconds: 7.910575,
      },
    ],
    range: "last_7_days",
    start: "2021-11-12T16:00:00Z",
    status: "ok",
    timeout: 15,
    timezone: "Asia/Shanghai",
    total_seconds: 122199.609451,
    total_seconds_including_other_language: 179875.088206,
    user_id: "8f0483ab-ef6c-4a7e-9f32-a48b185b367a",
    username: "sssgoEasy",
    writes_only: false,
  },
};
