name: CI

#on: [push]

on:
  workflow_dispatch:
  schedule:
    - cron: "20 0 * * *" # 每天 0：20 时运行

jobs: # 工作流
  build: # 自定义名称
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps: # 步骤
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 
      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: run toXml.js 
        run: npm install && npm run build:xml
